"""initial

Revision ID: edfbc71bbb28
Revises: 
Create Date: 2025-05-27 02:53:41.294612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfbc71bbb28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('integrations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('integrations_user_id_fkey', 'integrations', type_='foreignkey')
    op.create_foreign_key(None, 'integrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'integrations', type_='foreignkey')
    op.create_foreign_key('integrations_user_id_fkey', 'integrations', 'users', ['user_id'], ['id'])
    op.alter_column('integrations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_user_id_fkey', 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
